version: '3'
services:
  load-data:
    build: ingest/.
    image: "test/project1-ingest"
    volumes:
     - /mnt/data/:/data

  train:
    build: train/.
    image: "test/iris-train-keras"
    volumes:
      - ./train/:/src
      - /mnt/data:/data
    ports:
      - 16006:6006
    depends_on: 
      - "load-data"
