version: '3'
services:
  load-data:
    build: ingest/.
    image: "test/project1-ingest"
    volumes:
     - ./ingest/:/code

  train:
    build: train/.
    image: "test/tensorflow"
    volumes:
      - ./train/:/code
      - /mnt/data:/data
